<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Game;

/**
 * PositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $x
     * @param $y
     * @param Game $game
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByCoordinates($x, $y, Game $game){
        $qb = $this->createQueryBuilder('p')
            ->where('p.posX = :x')
            ->andWhere('p.posY = :y')
            ->andWhere('p.game = :game')
            ->setParameter('x', $x)
            ->setParameter('y', $y)
            ->setParameter('game', $game);

        return $qb->getQuery()->getSingleResult();

    }

}
