<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Game;
use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @param Game $game
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOpponentByMeAndGame(User $user, Game $game){
        $qb = $this->createQueryBuilder('u')
            ->where('u.game = :game')
            ->andWhere('u.id != :id')
            ->setParameter('id', $user->getId())
            ->setParameter('game', $game);

        return $qb->getQuery()->getSingleResult();

    }
    
}
